 export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
 export const USER_LOGIN_SICCESS = 'USER_LOGIN_SICCESS'
 export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

 export const USER_LOGOUT = 'USER_LOGOUT'
